const express = require('express')
const router = express.Router()
const { supabase, supabaseAdmin } = require('../supabase')
const { body, validationResult } = require('express-validator')
const auth = require ('../middleware/auth')
const { ensureProfile } = require ('../middleware/auth')

// ---------- Strong-password helper ----------
// Reused by register + change-password.  Returns a human-readable
// error string if the password fails any rule, null if it passes.
const STRONG_PASSWORD_REGEX = /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?`~]).+$/
function validateStrongPassword(value) {
  if (typeof value !== 'string' || value.length < 8)
    return 'Password must be at least 8 characters.'
  if (value.length > 128)
    return 'Password must be at most 128 characters.'
  if (!/[A-Z]/.test(value))
    return 'Password must contain at least one uppercase letter.'
  if (!/[a-z]/.test(value))
    return 'Password must contain at least one lowercase letter.'
  if (!/\d/.test(value))
    return 'Password must contain at least one number.'
  if (!STRONG_PASSWORD_REGEX.test(value))
    return 'Password must contain at least one special character (!@#$%^&* etc.).'
  return null
}

// This will acts as the api/auth/register
// Take note: Public - Anyone can create an account

router.post('/register', [
    body('email')
        .isEmail()
        .withMessage('Please enter a valid email'),
    body('password')
        .custom((value) => {
            const err = validateStrongPassword(value);
            if (err) throw new Error(err);
            return true;
        }),
    body('username')
        .isLength({ min: 3, max: 20 })
        .withMessage('Username must be between 3 and 20 characters')
        .matches(/^[a-zA-Z0-9_]+$/)
        .withMessage('Username can only contain letters, numbers, and underscores'),
], async (req, res) => {

    const errors = validationResult(req)
    if (!errors.isEmpty()) {
        return res.status(400).json({ message: errors.array()[0].msg })
    }

    const { email, password, username } = req.body

    try {
        // Step 1 - Create auth account in Supabase Auth
        const { data: authData, error: authError } = await supabase.auth.signUp({
            email,
            password
        })

        if (authError) {
            console.error('Supabase auth signup error:', authError)
            return res.status(400).json({ message: 'Registration failed. Please try again.' })
        }

        // auth_id is the UUID from Supabase Auth
        // this links our public.users row to auth.users
        const authUserId = authData.user.id

        // Step 2 - Insert profile row using auth_id, not id directly
        // id (bigint) is auto-generated by Supabase 
        // auth_id (uuid) links to auth.users
        const { error: profileError } = await supabase
            .from('users')
            .insert({
                auth_id: authUserId,
                user_name: username,
                email: email,
                role: 'viewer',
                account_status: 'active',
                created_at: new Date().toISOString()
            })

        if (profileError) {
            console.error('Profile insert error:', profileError)
            return res.status(400).json({ message: 'Could not create profile. Username may already be taken.' })
        }

        return res.status(201).json({
            message: 'Account created successfully.'
        })

    } catch (err) {
        console.error('Register error:', err)
        return res.status(500).json({ message: 'Server error. Please try again later.' })
    }
})

// POST - api/auth/login
// Public - Registered users ONLY 

router.post('/login', [
    body('email')
        .isEmail()
        .withMessage('Please enter a valid email'),
    body('password')
        .notEmpty()
        .withMessage('Password is required'),
], async (req, res) => {

    const errors = validationResult(req)
    if (!errors.isEmpty()) {
        return res.status(400).json({ message: errors.array()[0].msg })
    }

    const { email, password } = req.body

    try {
        // Step 1 - Authenticate with Supabase Auth
        const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
            email,
            password
        })

        if (authError) {
            return res.status(401).json({ message: 'Invalid email or password.' })
        }

        const authUserId = authData.user.id
        const token = authData.session.access_token

        // Step 2 - Retrieve profile using auth_id (uuid), not id (bigint)
        // We also select the internal bigint id - needed for all downstream writes
        let { data: profile, error: profileError } = await supabase
            .from('users')
            .select('id, user_name, role, account_status, school_id')
            .eq('auth_id', authUserId)
            .single()

        // Edge case: auth entry exists (e.g. Google OAuth created it) but
        // no public.users row yet — auto-provision the profile here so the
        // login response succeeds. After this, the auth middleware will
        // always find the profile on subsequent calls.
        if ((profileError || !profile) && authUserId) {
            profile = await ensureProfile(authUserId, { email })
            if (profile) profileError = null
        }

        if (profileError || !profile) {
            return res.status(401).json({ message: 'Invalid email or password.' })
        }

        // Step 3 - Block suspended accounts
        if (profile.account_status === 'suspended') {
            return res.status(403).json({ message: 'Your account has been suspended. Contact support.' })
        }

        // Step 4 - Return token + both IDs + role to frontend
        // id = bigint, used for all note/answer/question writes downstream
        // auth_id = uuid, used for auth comparisons
        return res.status(200).json({
            token,
            user: {
                id: profile.id,
                auth_id: authUserId,
                username: profile.user_name,
                role: profile.role,
                school_id: profile.school_id
            }
        })

    } catch (err) {
        console.error('Login error:', err)
        return res.status(500).json({ message: 'Server error. Please try again later.' })
    }
})

// POST api/auth/logout
// PROTECTED - must be logged in to log out

router.post('/logout', auth, async (req, res) => {
    try {
        const { error } = await supabase.auth.signOut()

        if (error) {
            return res.status(500).json({ message: 'Logout failed. Please try again.' })
        }

        return res.status(200).json({ message: 'Logged out successfully.' })

    } catch (err) {
        console.error('Logout error:', err)
        return res.status(500).json({ message: 'Server error. Please try again later.' })
    }
})

// POST api/auth/change-password
// PROTECTED - must be logged in to change your password.
// Verifies the current password against Supabase Auth, then updates the
// password via the service-role admin API. The existing session stays
// valid, so no re-login is forced.

router.post('/change-password', auth, [
    body('current_password')
        .notEmpty()
        .withMessage('Current password is required'),
    body('new_password')
        .custom((value) => {
            const err = validateStrongPassword(value);
            if (err) throw new Error(err);
            return true;
        }),
], async (req, res) => {

    const errors = validationResult(req)
    if (!errors.isEmpty()) {
        return res.status(400).json({ message: errors.array()[0].msg })
    }

    const { current_password, new_password } = req.body

    try {
        // Step 1 - Look up the user's auth email (auth_id -> users row).
        const { data: userRow, error: lookupError } = await supabase
            .from('users')
            .select('email')
            .eq('auth_id', req.user.auth_id)
            .maybeSingle()

        if (lookupError || !userRow || !userRow.email) {
            console.error('[auth] change-password lookup error:', lookupError)
            return res.status(400).json({ message: 'Could not look up your account.' })
        }

        // Step 2 - Verify the current password actually matches.
        const { error: signInError } = await supabase.auth.signInWithPassword({
            email: userRow.email,
            password: current_password,
        })
        if (signInError) {
            return res.status(401).json({ message: 'Current password is incorrect.' })
        }

        // Step 3 - Update the password (service role, by auth UUID).
        const { error: updateError } = await supabaseAdmin.auth.admin.updateUserById(
            req.user.auth_id,
            { password: new_password }
        )
        if (updateError) {
            console.error('[auth] change-password update error:', updateError)
            return res.status(500).json({ message: 'Could not update your password. Please try again.' })
        }

        return res.status(200).json({ message: 'Password updated successfully.' })

    } catch (err) {
        console.error('[auth] change-password exception:', err)
        return res.status(500).json({ message: 'Server error. Please try again later.' })
    }
})

// POST api/auth/signout-all
// PROTECTED - ends every active session for this user, including the
// current one (Supabase Auth admin.signOut with 'global' scope). The
// frontend clears its token and returns to the home page afterwards.

router.post('/signout-all', auth, async (req, res) => {
    const token = (req.headers.authorization || '').split(' ')[1]
    if (!token) {
        return res.status(400).json({ message: 'No session token found.' })
    }

    try {
        const { error } = await supabaseAdmin.auth.admin.signOut(token, 'global')
        if (error) {
            console.error('[auth] signout-all error:', error)
            return res.status(500).json({ message: 'Could not sign out all sessions.' })
        }
        return res.status(200).json({ message: 'Signed out of all sessions.' })
    } catch (err) {
        console.error('[auth] signout-all exception:', err)
        return res.status(500).json({ message: 'Server error. Please try again later.' })
    }
})

module.exports = router