const express = require('express')
const router = express.Router()
const { supabase } = require('../supabase')
const { body, validationResult } = require('express-validator')
const auth = require ('../middleware/auth')

// This will acts as the api/auth/register
// Take note: Public - Anyone can create an account

router.post('/register', [
    body('email')
        .isEmail()
        .withMessage('Please enter a valid email'),
    body('password')
        .isLength({ min: 8 })
        .withMessage('Password must be at least 8 characters'),
    body('username')
        .isLength({ min: 3, max: 20 })
        .withMessage('Username must be between 3 and 20 characters')
        .matches(/^[a-zA-Z0-9_]+$/)
        .withMessage('Username can only contain letters, numbers, and underscores'),
], async (req, res) => {

    const errors = validationResult(req)
    if (!errors.isEmpty()) {
        return res.status(400).json({ message: errors.array()[0].msg })
    }

    const { email, password, username } = req.body

    try {
        // Step 1 - Create auth account in Supabase Auth
        const { data: authData, error: authError } = await supabase.auth.signUp({
            email,
            password
        })

        if (authError) {
            console.error('Supabase auth signup error:', authError)
            return res.status(400).json({ message: 'Registration failed. Please try again.' })
        }

        // auth_id is the UUID from Supabase Auth
        // this links our public.users row to auth.users
        const authUserId = authData.user.id

        // Step 2 - Insert profile row using auth_id, not id directly
        // id (bigint) is auto-generated by Supabase 
        // auth_id (uuid) links to auth.users
        const { error: profileError } = await supabase
            .from('users')
            .insert({
                auth_id: authUserId,
                user_name: username,
                email: email,
                role: 'viewer',
                account_status: 'active',
                created_at: new Date().toISOString()
            })

        if (profileError) {
            console.error('Profile insert error:', profileError)
            return res.status(400).json({ message: 'Could not create profile. Username may already be taken.' })
        }

        return res.status(201).json({
            message: 'Account created successfully.'
        })

    } catch (err) {
        console.error('Register error:', err)
        return res.status(500).json({ message: 'Server error. Please try again later.' })
    }
})

// POST - api/auth/login
// Public - Registered users ONLY 

router.post('/login', [
    body('email')
        .isEmail()
        .withMessage('Please enter a valid email'),
    body('password')
        .notEmpty()
        .withMessage('Password is required'),
], async (req, res) => {

    const errors = validationResult(req)
    if (!errors.isEmpty()) {
        return res.status(400).json({ message: errors.array()[0].msg })
    }

    const { email, password } = req.body

    try {
        // Step 1 - Authenticate with Supabase Auth
        const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
            email,
            password
        })

        if (authError) {
            return res.status(401).json({ message: 'Invalid email or password.' })
        }

        const authUserId = authData.user.id
        const token = authData.session.access_token

        // Step 2 - Retrieve profile using auth_id (uuid), not id (bigint)
        // We also select the internal bigint id - needed for all downstream writes
        const { data: profile, error: profileError } = await supabase
            .from('users')
            .select('id, user_name, role, account_status, school_id')
            .eq('auth_id', authUserId)
            .single()

        if (profileError || !profile) {
            return res.status(401).json({ message: 'Invalid email or password.' })
        }

        // Step 3 - Block suspended accounts
        if (profile.account_status === 'suspended') {
            return res.status(403).json({ message: 'Your account has been suspended. Contact support.' })
        }

        // Step 4 - Return token + both IDs + role to frontend
        // id = bigint, used for all note/answer/question writes downstream
        // auth_id = uuid, used for auth comparisons
        return res.status(200).json({
            token,
            user: {
                id: profile.id,
                auth_id: authUserId,
                username: profile.user_name,
                role: profile.role,
                school_id: profile.school_id
            }
        })

    } catch (err) {
        console.error('Login error:', err)
        return res.status(500).json({ message: 'Server error. Please try again later.' })
    }
})

// POST api/auth/logout
// PROTECTED - must be logged in to log out

router.post('/logout', auth, async (req, res) => {
    try {
        const { error } = await supabase.auth.signOut()

        if (error) {
            return res.status(500).json({ message: 'Logout failed. Please try again.' })
        }

        return res.status(200).json({ message: 'Logged out successfully.' })

    } catch (err) {
        console.error('Logout error:', err)
        return res.status(500).json({ message: 'Server error. Please try again later.' })
    }
})

// this is where the functions will be located 
// POST /api/auth/register
// POST /api/auth/login
// POST /api/auth/logout

module.exports = router